### ISSUE TITLE
some func may now be built into Rails

### ISSUE THREAD

**Issue by jrochkind** [sds/db-query-matchers#62]
I only just noticed that Rails now exposes `assert_queries` and `assert_no_queries` methods for code to use in testing. 

I learned about it from this video: https://www.youtube.com/watch?v=hd330GmxsWY

I think these were made public methods for developers to use only in Rails 7.1. I still can't actually find public Rails documentation on it, maybe someone else can?

That definitely duplicates some functionality in this gem, and may make it superfluous? I haven't totally analyzed what features are covered, and what features may exist in this gem that still not covered in Rails.

**Comment by jrochkind** [comment]
oops, maybe not yet in Rails 7.1, but in next Rails?  The PR with commits, if you want to track it: https://github.com/rails/rails/pull/50281

**Comment by sds** [comment]
Thanks for mentioning. Would encourage folks to use whatever functionality that comes with Rails directly, since it'll be kept up to date as Rails continues to evolve.
